# Generated by Django 5.2.4 on 2025-07-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dec',
            new_name='desc',
        ),
    ]
